### ISSUE TITLE
compatibility with BOP nether biomes

### ISSUE THREAD

**Issue by 0Navis0** [progwml6/Natura#352]
When the option for overriding the nether in Natura config is true, the BOP nether biomes don't spawn more, and when it's false, the BOP biomes spawn but the tainted soil and heat sand don't spawn more.

**Comment by 0Navis0** [comment]
Is there a fix planed ?

**Comment by alexbegt** [comment]
Is this for 1.10.2 or 1.11.2?

**Comment by 0Navis0** [comment]
BOP added back nether biomes only on 1.11.2

**Comment by 0Navis0** [comment]
You should maybe generate the Netherite as a biome and not as a pseudo dimension.

**Comment by progwml6** [comment]
Natura does not add biomes and never will

**Comment by trainzkid** [comment]
Both the Natura generation and Biomes O Plenty nether biomes are working together for me, though it may be because I'm using Just Enough Dimensions and setting the Nether's `worldProvider` to Biomes O Plenty's `worldProvider`.

Either that or it's fixed now.

**Comment by 0Navis0** [comment]
No it doesn't work, you don't get any tainted soil and heat sand since BOP override the nether provider as much as Natura, and prevents the netherite pseudo dimension to generate. So you get only the trees and muschrooms.

**Comment by 0Navis0** [comment]
Is there anything new about this isssue ?

**Comment by 0Navis0** [comment]
Now Natura doesn't prevent more the BiomesOPlenty and NetherEx biomes to spawn in the nether when the nether override option is true, but the tainted soil and heat sand still don't spawn.
